# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = antlr_tutorial
SUB_SRC_FILES = \
    preface.xml \
    ch01_antlr_intro.xml \
    ch02_antlr_dev_process.xml \
    ch03_antlr_grammar.xml \
    ch04_antlr_dev_tool.xml \
    ch05_antlr_common_issue.xml \
    ch06_antlr_summary.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk